spring.application.name=ap-csa-practice

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=apcsadb
# If your MongoDB requires authentication, uncomment the following two lines and fill in your username and password
# spring.data.mongodb.username=your_username
# spring.data.mongodb.password=your_password